version: 1.0.0.{build}

environment:
  configuration: Release
  node_version: "8.9.4"

image: Visual Studio 2017

init:
- ps: |
    Install-Product node $env:node_version

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- '%USERPROFILE%\.nuget\packages -> **\*.csproj'
- '%LOCALAPPDATA%\npm-cache -> **\package.json'         # npm cache
- 'node_modules -> **\package.json'                     # local npm modules

before_build:
- ps: |
    appveyor-retry choco install octopustools
    appveyor-retry dotnet restore

build_script:
- ps: |
    dotnet build .\src\tacos.mvc\ --configuration $Env:configuration

after_build:
- ps: |
    dotnet publish .\src\tacos.mvc\ --output ..\..\publish\tacos.mvc --configuration $Env:configuration
    octo pack --id Tacos.Mvc --version $Env:APPVEYOR_BUILD_VERSION --releaseNotes $Env:APPVEYOR_REPO_COMMIT_MESSAGE --basepath .\publish\tacos.mvc\ --outFolder .\artifacts\

#test_script:
#- ps: dotnet test .\tests\tacos.tests\tacos.tests.csproj

artifacts:
- path: artifacts\**\*.nupkg
  name: nugetweb

deploy:
- provider: NuGet
  server: https://scruffy.caes.ucdavis.edu/nuget/packages
  api_key:
    secure: 0bPmdZ5IVKjvNHKPjW4pNSmM223U0YV/oQKJ/NdN/CE=
  on:
    branch: master

notifications:
- provider: Slack
  incoming_webhook:
    secure: LuxmN+FnchXMF+YqT22T01ThGevYieMVf68dkPTFWdS1LSps+N7enGRfbwrRuAM2ZRuSxendJrv45G9s0uKeg0XTUHeESC8qRTLSfIpcykQ=
  channel: caes-development
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
