# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET.

trigger:
- master

pr:
- master

name: 1.1.$(Date:yyMM).$(Build.BuildId)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactName: 'drop'
  publishOutput: '$(Build.ArtifactStagingDirectory)/webapp'
  testServiceConnection: 'UC Davis CAES Test'
  testWebAppName: 'tacos-test'
  testEnvironmentName: 'tacos-test'
  prodServiceConnection: 'UC Davis CAES Production'
  prodWebAppName: 'tacosucd'
  prodEnvironmentName: 'tacos-production'

stages:
- stage: Test
  jobs:
  - job: Test
    steps:
    - task: NodeTool@0
      displayName: 'Use Node 22'
      inputs:
        versionSpec: '22.x'

    - task: Npm@1
      displayName: 'Install Npm Packages'
      inputs:
        command: 'custom'
        customCommand: 'install'
        workingDir: './src/tacos.mvc'

    - task: UseDotNet@2
      displayName: 'Use .NET 10 sdk'
      inputs:
        packageType: 'sdk'
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: 'Run Server Tests'
      inputs:
        command: 'test'
        projects: './Test/Test.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: Npm@1
      displayName: 'Run Client Lint'
      inputs:
        command: 'custom'
        workingDir: './src/tacos.mvc'
        customCommand: 'run lint'

    - task: Npm@1
      displayName: 'Run Client Tests'
      inputs:
        command: 'custom'
        workingDir: './src/tacos.mvc'
        customCommand: 'run test'

- stage: Publish
  dependsOn: Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Publish
    steps:
    - task: NodeTool@0
      displayName: 'Use Node 22'
      inputs:
        versionSpec: '22.x'

    - task: UseDotNet@2
      displayName: 'Use .NET 10 sdk'
      inputs:
        packageType: 'sdk'
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish tacos.mvc'
      inputs:
        command: 'publish'
        publishWebProjects: false
        zipAfterPublish: false
        modifyOutputPath: false
        projects: './src/tacos.mvc/tacos.mvc.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(publishOutput)'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish web app artifact'
      inputs:
        targetPath: '$(publishOutput)'
        artifact: '$(artifactName)'

- stage: Deploy_Test
  displayName: 'Deploy Test'
  dependsOn: Publish
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: Deploy_Test
    displayName: 'Deploy to test web app'
    environment: '$(testEnvironmentName)'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(artifactName)'

          - task: AzureWebApp@1
            displayName: 'Deploy tacos-test'
            inputs:
              azureSubscription: '$(testServiceConnection)'
              appType: 'webApp'
              appName: '$(testWebAppName)'
              package: '$(Pipeline.Workspace)/$(artifactName)'

- stage: Deploy_Prod
  displayName: 'Deploy Production'
  dependsOn: Deploy_Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: Deploy_Prod
    displayName: 'Deploy to production web app'
    environment: '$(prodEnvironmentName)'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: '$(artifactName)'

          - task: AzureWebApp@1
            displayName: 'Deploy tacosucd'
            inputs:
              azureSubscription: '$(prodServiceConnection)'
              appType: 'webApp'
              appName: '$(prodWebAppName)'
              package: '$(Pipeline.Workspace)/$(artifactName)'
