# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET.

trigger:
- master

pr:
- master

name: 1.1.$(Date:yyMM).$(Build.BuildId)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Test
  jobs:
  - job: Test
    steps:
    - task: NodeTool@0
      displayName: 'Use Node 22'
      inputs:
        versionSpec: '22.x'

    - task: Npm@1
      displayName: 'Install Npm Packages'
      inputs:
        command: 'custom'
        customCommand: 'install --legacy-peer-deps'
        workingDir: './src/tacos.mvc'

    - task: UseDotNet@2
      displayName: 'Use .NET 10 sdk'
      inputs:
        packageType: 'sdk'
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: 'Run Server Tests'
      inputs:
        command: 'test'
        projects: './Test/Test.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: Npm@1
      displayName: 'Run Client Tests'
      inputs:
        command: 'custom'
        workingDir: './src/tacos.mvc'
        customCommand: 'run test'

- stage: Publish
  jobs:
  - job: Publish
    steps:
    - task: NodeTool@0
      displayName: 'Use Node 22'
      inputs:
        versionSpec: '22.x'

    - task: UseDotNet@2
      displayName: 'Use .NET 10 sdk'
      inputs:
        packageType: 'sdk'
        useGlobalJson: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish tacos.mvc'
      inputs:
        command: 'publish'
        publishWebProjects: false
        zipAfterPublish: false
        modifyOutputPath: false
        projects: './src/tacos.mvc/tacos.mvc.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/'

    - task: PublishBuildArtifacts@1
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      displayName: 'Publish Build Artifacts for master branch builds'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
