# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet restore
    displayName: dotnet restore

  - script: dotnet build .\src\tacos.mvc\ --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet publish .\src\tacos.mvc\ --output $(Build.ArtifactStagingDirectory) --configuration $(buildConfiguration)
    displayName: 'dotnet publish $(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    displayName: 'publish artifact'
    inputs:
      ArtifactName: tacos.mvc
      PathtoPublish: $(Build.ArtifactStagingDirectory)
