CREATE TABLE [dbo].[Requests]
(
    [Id]                       INT IDENTITY (1, 1)	NOT NULL,
	[Approved]                 BIT					NULL,
    [CalculatedTotal]          FLOAT (53)			NOT NULL,
    [AnnualizedTotal]          FLOAT (53)			NOT NULL,
    [AverageEnrollment]        FLOAT(53)			NOT NULL,
    [AverageSectionsPerCourse] FLOAT(53)			NOT NULL,
    [TimesOfferedPerYear]      FLOAT(53)			NOT NULL,
    [ExceptionReason]          NVARCHAR (MAX)		NULL,
    [ExceptionTotal]           FLOAT (53)			NOT NULL,
    [ExceptionAnnualizedTotal] FLOAT (53)			NOT NULL,
    [Exception]                BIT					NOT NULL,
    [Department]               NVARCHAR (MAX)		NULL,
    [CourseNumber]             NVARCHAR (MAX)		NULL,
    [CourseType]               NVARCHAR (MAX)		NULL,
    [RequestType]              NVARCHAR (MAX)		NULL,
	[UpdatedBy]                NVARCHAR (MAX)		NULL,
    [UpdatedOn]                DATETIME2 (7)		NOT NULL,
    CONSTRAINT [PK_Requests] PRIMARY KEY CLUSTERED ([Id] ASC),
);
