name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      name: Checkout

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.403' # SDK Version to use.
