name: CI
  
on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      name: Checkout code
      
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Run npm
      run: cd ./src/tacos.mvc/ && npm install
      run: cd ./src/tacos.mvc/ && npm run build

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.403' # SDK Version to use.

    - name: Run build
      run: dotnet build ./src/tacos.mvc/tacos.mvc.csproj --configuration Release
